[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  external_node_modules = []

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "autoplay=*, encrypted-media=*, fullscreen=*, picture-in-picture=*, accelerometer=*, gyroscope=*"

